In [2]:
import torch

In [3]:
from models.imagenet_resnet import resnet18, resnet50
from models.cifar_resnet import resnet20, resnet32, resnet56
from torch import nn as nn 

from scipy.spatial.distance import cdist
import numpy as np

import gudhi as gd
from gudhi import wasserstein

import time

In [4]:
import numpy as np
from ripser import ripser
from persim import plot_diagrams
from gph.python import ripser_parallel
from scipy.spatial.distance import pdist, squareform
#import ripserplusplus as rpp_py
import time

In [5]:
pc = np.random.random((10, 3))
#pc[0] = [0,0,0]
#pc[1] = [0,0,0]
#pc[2] = [0,0,0]
#pc[3] = [0,0,0]
dist = squareform(pdist(pc))
t1 = time.time()
res= ripser_parallel(dist, metric="precomputed", maxdim=0, n_threads=-1, return_generators=True)

In [5]:
bd_pairs = res['dgms']
generators = res['gens']

In [6]:
len(bd_pairs[0])

10

In [7]:
len(generators[0].T[0])

9

In [8]:
for i in generators[0]:
    print(dist[i[1],i[2]], i)

0.1346709550322222 [6 6 5]
0.15222066817413954 [9 9 0]
0.19498074880312607 [5 6 4]
0.23217186909711773 [3 3 2]
0.2737336380482728 [7 7 2]
0.28156185075722734 [8 8 7]
0.3808696803226943 [2 7 6]
0.500549921259722 [1 1 0]
0.5265074216304618 [4 8 1]


In [9]:
bd_pairs[0]

array([[0.        , 0.13467096],
       [0.        , 0.15222067],
       [0.        , 0.19498076],
       [0.        , 0.23217186],
       [0.        , 0.27373365],
       [0.        , 0.28156185],
       [0.        , 0.3808697 ],
       [0.        , 0.5005499 ],
       [0.        , 0.52650744],
       [0.        ,        inf]], dtype=float32)

CifarResNet : Depth : 20 , Layers for each block : 3


<All keys matched successfully>

In [20]:
for index, item in enumerate(model.parameters()):
    if index in mask_index:
        layer_weight = item#.data

In [21]:
weight_vec = layer_weight.view(layer_weight.size()[0], -1).data

In [22]:
#weight_vec[0] = torch.zeros(576)
#weight_vec[10] = torch.zeros(576)
#weight_vec[25] = torch.zeros(576)
#weight_vec[-1] = torch.zeros(576)

In [23]:
weight_torch = layer_weight.data


In [24]:
similar_matrix = cdist(weight_vec, weight_vec, 'euclidean')

In [25]:
similar_matrix

array([[0.        , 0.48654228, 0.80298269, ..., 1.23383602, 0.94167295,
        1.17562349],
       [0.48654228, 0.        , 0.80509333, ..., 1.33953   , 0.96451191,
        1.16334786],
       [0.80298269, 0.80509333, 0.        , ..., 1.36422852, 1.32524842,
        1.31138729],
       ...,
       [1.23383602, 1.33953   , 1.36422852, ..., 0.        , 1.51869882,
        1.04567413],
       [0.94167295, 0.96451191, 1.32524842, ..., 1.51869882, 0.        ,
        1.34160619],
       [1.17562349, 1.16334786, 1.31138729, ..., 1.04567413, 1.34160619,
        0.        ]])

In [26]:
topo_res = ripser_parallel(similar_matrix, metric="precomputed",
                           maxdim=0, n_threads=-1, return_generators=True)
bd_pairs = topo_res['dgms']
generators = topo_res['gens']

In [27]:
len(generators[0].T[0]), len(weight_vec)

(63, 64)

In [28]:
np.unique(generators[0].T[0])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [19]:
bd_pairs

[array([[0.       , 1.83569  ],
        [0.       , 1.8358666],
        [0.       , 1.8362292],
        [0.       , 1.837525 ],
        [0.       , 1.8380343],
        [0.       , 1.847869 ],
        [0.       , 1.8494601],
        [0.       , 1.8545004],
        [0.       , 1.8547724],
        [0.       , 1.8550887],
        [0.       , 1.85703  ],
        [0.       , 1.8576427],
        [0.       , 1.8576906],
        [0.       , 1.8588759],
        [0.       , 1.8594713],
        [0.       , 1.8611175],
        [0.       , 1.8612108],
        [0.       , 1.8633038],
        [0.       , 1.8665721],
        [0.       , 1.8689307],
        [0.       , 1.8693581],
        [0.       , 1.8709112],
        [0.       , 1.8709805],
        [0.       , 1.8711605],
        [0.       , 1.8729482],
        [0.       , 1.8730757],
        [0.       , 1.8736153],
        [0.       , 1.8745905],
        [0.       , 1.8763587],
        [0.       , 1.8774952],
        [0.       , 1.8782704],
        

In [20]:
similar_pruned_num = int(64*0.2)
similar_pruned_num

12

In [21]:
len(generators[0]),len(bd_pairs[0]), len(similar_matrix)

(63, 64, 64)

In [22]:
generators

(array([[14, 14, 11],
        [ 5,  5,  3],
        [24, 24,  5],
        [52, 52, 31],
        [54, 54,  5],
        [19, 19, 15],
        [43, 43, 11],
        [47, 47, 14],
        [37, 37, 24],
        [45, 45, 30],
        [53, 53, 52],
        [ 3, 24, 22],
        [29, 29,  8],
        [31, 53, 30],
        [11, 47, 25],
        [32, 32,  7],
        [25, 11,  3],
        [30, 45, 22],
        [63, 63, 52],
        [ 8, 29, 23],
        [22, 63, 29],
        [23,  5,  4],
        [27, 27, 14],
        [ 4, 37, 18],
        [59, 59, 34],
        [18, 63, 36],
        [36, 47, 39],
        [39, 45, 12],
        [12, 52,  2],
        [34, 59, 54],
        [ 2, 24,  1],
        [62, 62, 10],
        [46, 46, 22],
        [ 1, 46, 15],
        [50, 50, 29],
        [15, 24,  7],
        [ 7, 54,  0],
        [ 0, 46, 17],
        [51, 51, 24],
        [35, 35, 24],
        [44, 44, 11],
        [61, 61, 15],
        [60, 60, 41],
        [17, 24, 13],
        [38, 38, 30],
        [5

In [23]:
len(generators[0])

63

In [49]:

from scipy.spatial import distance

In [50]:
cluster = []
num_clusters = 0
to_drop = 10
for el in generators[0]:
    stopping_criteria = sum([len(i)-1 for i in cluster]) == to_drop
    if stopping_criteria:
        break
    if len(cluster)>0:
        cl_indx = [i for i in range(len(cluster)) if (el[1] in cluster[i] or el[2] in cluster[i])]
        if len(cl_indx)>2:
            print("Error")
            raise()
        if len(cl_indx)==0:
            cluster.append({el[1],el[2]})
        
        # add to an existing cluster
        if len(cl_indx)==1:
            cluster[cl_indx[0]].add(el[1])
            cluster[cl_indx[0]].add(el[2])
        
        # merge clusters
        if len(cl_indx)==2:
            if cl_indx[1] > cl_indx[0]:
                cluster_1, cluster_2 = cluster.pop(cl_indx[1]), cluster.pop(cl_indx[0])
            else:
                cluster_1, cluster_2 = cluster.pop(cl_indx[0]), cluster.pop(cl_indx[1])
            cluster_1 |= cluster_2
            cluster.append(cluster_1)
        
    else:
        cluster.append({el[1],el[2]})

In [51]:
cluster

[{11, 14, 43, 47}, {3, 5, 24, 37, 54}, {31, 52}, {15, 19}, {30, 45}]

In [59]:
filters_to_reinit = {}
# Go through the clusters and remove the most centered filter from the list to drop
for i in range(len(cluster)):
    sub_indexes = list(cluster[i])
    subvectors = weight_vec[sub_indexes]
    local_similarity_matrix = distance.cdist(subvectors, subvectors, 'euclidean')
    local_similar_sum = np.sum(np.abs(local_similarity_matrix), axis=0)
    # The most central filter
    similar_small_index = local_similar_sum.argsort()[0]
    #print(cluster[i])
    # Remove the most central filter from the list of filters to dropabs
    
    filters_to_reinit[sub_indexes[similar_small_index]] = torch.mean(subvectors.data, axis=0)
    cluster[i].remove(sub_indexes[similar_small_index])
    
filters_to_drop = list({x for _list in cluster for x in _list})

In [44]:
filters_to_reinit.keys(), filters_to_drop

(dict_keys([43, 24, 31, 15, 30]), [3, 37, 11, 47, 54])

In [58]:
cluster

[{11, 43, 47}, {3, 24, 37, 54}, {31}, {15}, {30}]

In [28]:
weight_vec.shape

torch.Size([64, 576])

In [60]:
zero_mask = torch.count_nonzero(weight_vec, dim=1)==0
how_many_are_already_0 = sum(zero_mask)

In [70]:
zero_mask[1]=True
zero_mask[5]=True

zero_mask[6]=True
zero_mask

tensor([False,  True, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False])

In [90]:
weight_vec[torch.argwhere(~zero_mask).flatten()].shape

NameError: name 'weight_torch' is not defined

In [98]:
original_indices = np.arange(len(weight_vec))
reduced_indices = original_indices[torch.argwhere(~zero_mask).flatten()]

In [99]:
reduced_indices[filters_to_drop],  filters_to_drop

(array([ 4, 40, 14, 50, 57]), [3, 37, 11, 47, 54])

In [100]:
reduced_indices

array([ 0,  2,  3,  4,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [85]:
torch.argwhere(~zero_mask).flatten()

tensor([ 0,  2,  3,  4,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
        39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
        57, 58, 59, 60, 61, 62, 63])

In [102]:
filters_to_reinit.keys()


dict_keys([43, 24, 31, 15, 30])

In [107]:
kernel_length = weight_torch.size()[1] * weight_torch.size()[2] * weight_torch.size()[3]
for x in range(0, len(filters_to_drop)):
    codebook[
    filters_to_drop[x] * kernel_length: (filters_to_drop[x] + 1) * kernel_length] = 0

In [108]:
codebook

array([1., 0., 1., 1., 1., 0., 0., 1., 1., 1.])

In [111]:
filters_to_drop[x] * kernel_length, (filters_to_drop[x] + 1) * kernel_length

(31104, 31680)

In [88]:
codebook = np.ones(10)
codebook [torch.argwhere(zero_mask).flatten()] = 0.
codebook

array([1., 0., 1., 1., 1., 0., 0., 1., 1., 1.])

In [112]:
torch.argwhere(zero_mask).flatten()


tensor([1, 5, 6])

In [113]:
filters_to_reinit

{43: tensor([-4.8341e-02, -4.8720e-02,  7.1807e-02,  2.5225e-04, -4.2191e-02,
         -1.1910e-02,  6.2158e-02, -7.0841e-03,  4.7229e-02,  2.7006e-02,
          6.2789e-02, -3.4458e-02, -1.6302e-02,  2.1500e-02,  2.3105e-03,
          1.4970e-02, -2.1820e-02, -3.7678e-02,  5.0312e-03, -3.2694e-03,
         -3.7495e-02, -4.9765e-02,  4.4089e-02,  1.3625e-02,  2.9618e-02,
         -6.1345e-02,  5.4923e-03, -2.3954e-02,  1.2731e-02,  7.5863e-02,
         -1.0076e-02, -3.4171e-02, -1.2854e-02,  3.9040e-03, -1.8586e-02,
         -8.0657e-02, -3.3592e-02,  4.4364e-02, -1.1235e-02, -6.0786e-02,
          3.5108e-02,  1.7534e-02,  1.4176e-02,  5.3376e-02, -4.9824e-02,
         -3.4924e-02,  1.4142e-02,  6.2311e-03,  6.6892e-03, -1.0227e-01,
         -2.3141e-02,  6.3364e-03,  9.4350e-03,  4.2865e-02, -1.0959e-02,
         -3.8946e-02, -4.9236e-03,  1.9381e-02, -1.6585e-02,  4.1736e-02,
          8.6434e-03, -5.0401e-02,  3.9664e-03,  4.7086e-02,  2.8266e-02,
          1.8004e-02, -1.2644e-02,

In [139]:
dictionary[new_key] = dictionary.pop(old_key)

{3, 4}

In [140]:
self.model

[{1, 2}, {5, 6}]

In [90]:
cluster = [{1,2}, {4,5}]
#cl_indx = [cl_el.key for cl_el in cluster if cl_el ] 

In [93]:
search = [8,1]
cluster_indx = [i for i in range(len(cluster)) if (search[0] in cluster[i] or search[1] in cluster[i])]
cluster_indx

[0]

In [101]:
a = {1,2}
a.add(1)
a.add(2)
a

{1, 2}

In [66]:
# key - cluster centers, value - removed values associated to this cluster
#print(generators[0][0], )
#print(generators[0][-1])
topo_dict ={generators[0][0][-1]: [generators[0][0][0]]}
print(topo_dict)
for i in generators[0][1:]:
    if i[0] in topo_dict.keys():
    # else - add to the existing cluster  
        print("key",i[0], "value", topo_dict[i[0]],"pair", i)
        topo_dict[i[0]].append(i[0])
        new_cluster_center = [value for value in i if value not in topo_dict[i[0]]]
        #print(new_cluster_center,"key",i[0], "value", topo_dict[i[0]],)
        #print(topo_dict.keys())
        assert len(new_cluster_center)==1
        new_cluster_center= new_cluster_center[0]
        topo_dict[new_cluster_center] = topo_dict.pop(i[0])
    else:
        if i[0] == i[1]:
            topo_dict[i[2]] = [i[0]] 
        if i[0] == i[2]:
            topo_dict[i[1]] = [i[0]]
    print(topo_dict)

{32: [40]}
{32: [40], 31: [63]}
{32: [40], 31: [63], 33: [53]}
key 33 value [53] pair [33 33  5]
{32: [40], 31: [63], 5: [53, 33]}
{32: [40], 31: [63], 5: [53, 33], 19: [30]}
key 31 value [63] pair [31 63 56]
{32: [40], 5: [53, 33], 19: [30], 56: [63, 31]}
key 56 value [63, 31] pair [56 56 26]
{32: [40], 5: [53, 33], 19: [30], 26: [63, 31, 56]}
{32: [40], 5: [53, 33], 19: [30], 26: [63, 31, 56], 9: [57]}
key 26 value [63, 31, 56] pair [26 26  7]
{32: [40], 5: [53, 33], 19: [30], 9: [57], 7: [63, 31, 56, 26]}
key 7 value [63, 31, 56, 26] pair [ 7 63 33]
{32: [40], 5: [53, 33], 19: [30], 9: [57], 33: [63, 31, 56, 26, 7]}
key 5 value [53, 33] pair [ 5 56 43]


AssertionError: 

In [26]:
a = {"a":1, "b":2}
a.fin

1

In [118]:
a = np.array([1,2,3])
b = np.array([4,5,6])
list(a)+list(b)

[1, 2, 3, 4, 5, 6]

In [38]:
generators[0]

array([[40, 40, 32],
       [63, 63, 31],
       [53, 53, 33],
       [33, 33,  5],
       [30, 30, 19],
       [31, 63, 56],
       [56, 56, 26],
       [57, 57,  9],
       [26, 26,  7],
       [ 7, 63, 33],
       [ 5, 56, 43],
       [42, 42, 33],
       [43, 26, 21],
       [37, 37, 33],
       [25, 25, 13],
       [ 9,  9,  8],
       [21, 42, 32],
       [58, 58, 26],
       [32, 33, 20],
       [20, 43, 19],
       [19, 30,  6],
       [ 6, 63, 62],
       [62, 58, 47],
       [47, 63, 57],
       [49, 49, 32],
       [60, 60,  6],
       [ 8, 63,  3],
       [ 3, 47, 46],
       [46, 57, 36],
       [36, 33, 29],
       [50, 50, 32],
       [48, 48, 32],
       [13, 13,  9],
       [27, 27, 26],
       [11, 11,  7],
       [29, 63, 17],
       [41, 41, 32],
       [17, 26,  2],
       [59, 59, 32],
       [ 2, 33,  4],
       [ 4, 32, 14],
       [52, 52,  6],
       [39, 39, 26],
       [44, 44,  7],
       [35, 35, 31],
       [14, 11,  1],
       [55, 55, 19],
       [45, 4

In [32]:
generators = generators[0]

In [64]:
## Discard zeroed filters from the analysis
[all(weight_vec[i]==0) for i in range(len(weight_vec))]

[True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True]

In [56]:
weight_vec[0]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [51]:
all([True, True,False])

False

In [29]:
similar_matrix

array([[0.        , 1.52385005, 1.35927818, ..., 1.44855973, 1.41682854,
        0.        ],
       [1.52385005, 0.        , 2.05590101, ..., 2.06784832, 2.0781654 ,
        1.52385005],
       [1.35927818, 2.05590101, 0.        , ..., 2.00105355, 2.01337252,
        1.35927818],
       ...,
       [1.44855973, 2.06784832, 2.00105355, ..., 0.        , 1.99306351,
        1.44855973],
       [1.41682854, 2.0781654 , 2.01337252, ..., 1.99306351, 0.        ,
        1.41682854],
       [0.        , 1.52385005, 1.35927818, ..., 1.44855973, 1.41682854,
        0.        ]])

In [130]:
weight_vec.shape

torch.Size([64, 576])

In [126]:
model.stage_3[2].conv_b.weight.shape , layer_weight.shape

(torch.Size([64, 64, 3, 3]), torch.Size([64, 64, 3, 3]))